version: '3.7'

services:
   posterr.database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: posterr
    ports:
    - "11433:1433"
    environment: 
      MSSQL_SA_PASSWORD: ea!@#12345
      MSSQL_PID: Developer
      ACCEPT_EULA: Y
    volumes:
       - C:\Posterr:/var/opt/mssql